name: Lint

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      LOCAL_BIN_DIR: "/home/runner/.local/bin"
    steps:
    - uses: actions/checkout@v4
    - name: Prepare PATH
      run: |
        echo "${PATH}"
        mkdir -p "${LOCAL_BIN_DIR}"
    - name: Download and Extract Pandoc
      uses: robinraju/release-downloader@v1.12
      with:
        repository: jgm/pandoc
        tag: 3.7.0.2
        fileName: pandoc-3.7.0.2-linux-amd64.tar.gz
        out-file-path: ${{ runner.temp }}
        extract: true
    - name: Download Typst
      uses: robinraju/release-downloader@v1.12
      with:
        repository: typst/typst
        tag: v0.13.1
        fileName: typst-x86_64-unknown-linux-musl.tar.xz
        out-file-path: ${{ runner.temp }}
        extract: false
    - name: Move deps to local bin
      run: |
        find "${RUNNER_TEMP}"
        mv "${RUNNER_TEMP}/pandoc-3.7.0.2/bin/pandoc" "${LOCAL_BIN_DIR}"
        tar -xvJf "${RUNNER_TEMP}/typst-x86_64-unknown-linux-musl.tar.xz" --strip-components=1 --wildcards '*/typst'
        mv typst "${LOCAL_BIN_DIR}"
    - name: Verify pandoc
      run: pandoc --version
    - name: Verify typst
      run: typst --version
    #- name: apt-deps
    #  run: |
    #    sudo apt install libsixel-bin -y
    #- name: Build
    #  run: cargo build
    #- name: Run tests
    #  run: cargo test
