name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: deps
      run: |
        sudo apt install pandoc libsixel-bin -y
        cargo install --locked typst-cli
        which typst
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
