name: Lint

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      LOCAL_BIN_DIR: "/home/runner/.local/bin"
      TEMP_DIR: "/home/runner/tmp"
    steps:
    - uses: actions/checkout@v4
    - name: Prepare PATH
      run: |
        echo "${PATH}"
        mkdir -p "${LOCAL_BIN_DIR}"
        mkdir -p "${TEMP_DIR}"
    - name: pandoc-dep
      run: |
        PANDOC_VERSION="3.7.0.2"
        PANDOC_ARCHIVE="pandoc-${PANDOC_VERSION}-linux-amd64.tar.gz"
        PANDOC_URL="https://github.com/jgm/pandoc/releases/download/${PANDOC_VERSION}/${PANDOC_ARCHIVE}"

        echo "Downloading Pandoc from ${PANDOC_URL}"
        curl -L "${PANDOC_URL}" -o "${RUNNER_TEMP}/pandoc.tar.gz"

        echo "Extracting pandoc executable to ${LOCAL_BIN_DIR}"
        tar -xvzf "${RUNNER_TEMP}/pandoc.tar.gz" --wildcards "*/pandoc" --strip-components=2
        mv pandoc "${LOCAL_BIN_DIR}"
    - name: Verify pandoc
      run: pandoc --version
    - name: Download Typst
      uses: robinraju/release-downloader@v1
      with:
        repository: typst/typst
        tag: v0.13.1
        fileName: typst-x86_64-unknown-linux-musl.tar.xz
        out-file-path: "${{ env.RUNNER_TEMP }}"
        extract: false
    - name: typst-dep
      run: |
        tar -xvJf "${RUNNER_TEMP}/typst-x86_64-unknown-linux-musl.tar.xz" --strip-components=1 --wildcards '*/typst'
        mv typst "${LOCAL_BIN_DIR}"
    - name: Verify typst
      run: typst --version
    #- name: apt-deps
    #  run: |
    #    sudo apt install libsixel-bin -y
    #- name: Build
    #  run: cargo build
    #- name: Run tests
    #  run: cargo test
