name: Release

on:
  workflow_dispatch: {}
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  publish-github:
    name: Publish on GitHub
    runs-on: ${{ matrix.config.OS }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - { OS: ubuntu-latest, TARGET: "x86_64-unknown-linux-gnu" }
          - { OS: macos-latest, TARGET: "x86_64-apple-darwin" }

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set the release version
        shell: bash
        run: echo "RELEASE_VERSION=${GITHUB_REF:11}" >> $GITHUB_ENV

      - name: Build binary
        uses: houseabsolute/actions-rust-cross@a448c4b13769d56b63b035024fef8577e1d81915
        with:
          command: build
          toolchain: 1.86.0
          target: ${{ matrix.config.TARGET }}
          args: "--locked --release"

      - name: Prepare release assets
        shell: bash
        run: |
          mkdir release/
          cp {LICENSE,README.md} release/
          cp target/${{ matrix.config.TARGET }}/release/logseq-srs release/
          mv release/ logseq-srs-${{ env.RELEASE_VERSION }}/

      - name: Create release artifacts
        shell: bash
        run: |
          tar -czvf logseq-srs-${{ env.RELEASE_VERSION }}-${{ matrix.config.TARGET }}.tar.gz \
            logseq-srs-${{ env.RELEASE_VERSION }}
          shasum -a 512 logseq-srs-${{ env.RELEASE_VERSION }}-${{ matrix.config.TARGET }}.tar.gz \
            > logseq-srs-${{ env.RELEASE_VERSION }}-${{ matrix.config.TARGET }}.tar.gz.sha512
