name: Release

on:
  push:
    tags:
      - "v*.*.*"

env:
  CARGO_TERM_COLOR: always

jobs:
  publish-github:
    name: Publish on GitHub
    runs-on: ${{ matrix.config.OS }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - { OS: ubuntu-latest, TARGET: "x86_64-unknown-linux-gnu" }
          - { OS: macos-latest, TARGET: "x86_64-apple-darwin" }

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set the release version
        shell: bash
        run: echo "RELEASE_VERSION=${GITHUB_REF:11}" >> $GITHUB_ENV

      - name: Build binary
        uses: houseabsolute/actions-rust-cross@a448c4b13769d56b63b035024fef8577e1d81915
        with:
          command: build
          toolchain: 1.89.0
          target: ${{ matrix.config.TARGET }}
          args: "--locked --release"

      - name: Prepare release assets
        shell: bash
        run: |
          mkdir release/
          cp {LICENSE.md,README.md} release/
          cp -r docs release/
          cp target/${{ matrix.config.TARGET }}/release/losrs release/
          mv release/ losrs-${{ env.RELEASE_VERSION }}/

      - name: Create release artifacts
        shell: bash
        run: |
          tar -czvf losrs-${{ env.RELEASE_VERSION }}-${{ matrix.config.TARGET }}.tar.gz \
            losrs-${{ env.RELEASE_VERSION }}/
          shasum -a 512 losrs-${{ env.RELEASE_VERSION }}-${{ matrix.config.TARGET }}.tar.gz \
            > losrs-${{ env.RELEASE_VERSION }}-${{ matrix.config.TARGET }}.tar.gz.sha512

      - name: Upload the release
        uses: svenstaro/upload-release-action@e2a63377780a8bacc68dcac9b0979ee20ad5a791
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: losrs-${{ env.RELEASE_VERSION }}-${{ matrix.config.TARGET }}.*
          file_glob: true
          overwrite: true
          release_name: ${{ env.RELEASE_VERSION }}
          tag: ${{ github.ref }}
          body: There is no changelog yet.
